-- Plantilla de tienda: migración para descuentos y categorías/subcategorías
-- Ejecutar en Supabase > SQL Editor

-- ============================================================
-- 1) DESCUENTOS
-- ============================================================

ALTER TABLE public."Productos"
ADD COLUMN IF NOT EXISTS descuento_porcentaje numeric(5,2) NOT NULL DEFAULT 0;

ALTER TABLE public."Productos"
DROP CONSTRAINT IF EXISTS productos_descuento_porcentaje_check;

ALTER TABLE public."Productos"
ADD CONSTRAINT productos_descuento_porcentaje_check
CHECK (descuento_porcentaje >= 0 AND descuento_porcentaje <= 100);

-- ============================================================
-- 2) CATEGORÍAS JERÁRQUICAS
-- ============================================================

CREATE TABLE IF NOT EXISTS public."Categorias" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  parent_id bigint NULL REFERENCES public."Categorias"(id) ON DELETE CASCADE,
  orden integer NOT NULL DEFAULT 1,
  activa boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS categorias_parent_id_idx
ON public."Categorias"(parent_id);

CREATE INDEX IF NOT EXISTS categorias_orden_idx
ON public."Categorias"(orden);

CREATE UNIQUE INDEX IF NOT EXISTS categorias_nombre_padre_unico_idx
ON public."Categorias"(LOWER(nombre), COALESCE(parent_id, 0));

-- ============================================================
-- 3) RLS DE CATEGORÍAS
-- ============================================================
-- Permite que la tienda pública lea categorías activas y que el
-- usuario autenticado del administrador pueda gestionarlas.

ALTER TABLE public."Categorias" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Categorias lectura pública" ON public."Categorias";
CREATE POLICY "Categorias lectura pública"
ON public."Categorias"
FOR SELECT
TO anon, authenticated
USING (activa = true OR auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Categorias gestión administrador" ON public."Categorias";
CREATE POLICY "Categorias gestión administrador"
ON public."Categorias"
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- ============================================================
-- LISTO
-- ============================================================
-- Después de ejecutar esto, Admin.tsx y App.tsx podrán usar:
--   Productos.descuento_porcentaje
--   Categorias.id
--   Categorias.nombre
--   Categorias.parent_id
--   Categorias.orden
--   Categorias.activa
